!Layer = 3              ; The layer in which the HDMA is rooted.
!Offset = $0000         ; How much is the table shifted
!ScrollFactor = 0       ; The division is exponential, using 2 as its base.

init:
	REP #$10
	LDX.w #sky_hdma_table
	STX $00
	LDA.b #sky_hdma_table>>16
	STA $02

	LDA.b #$70
	LDX.w #!big_hdma_decomp_buff_rg
	LDY.w #!big_hdma_decomp_buff_b

	JSL ScrollHDMA_init
main:
	REP #$20

	LDA #!big_hdma_decomp_buff_rg
	STA $00
	LDA #!big_hdma_decomp_buff_b
	STA $02

	LDA $1C+((!Layer-1)<<2)
	CLC : ADC.w #!Offset
	LSR #!ScrollFactor
	JML ScrollHDMA_main

;=======================================
; Scrolling Gradient
; Channels: Red, Green, Blue
; Table Size: 293
; No. of Writes: 464
; 
; Generated by GradientTool
;=======================================

sky_hdma_table:
db $2D,$26,$48,$8D
db $01,$26,$49,$8D
db $06,$26,$49,$8E
db $05,$27,$4A,$8E
db $03,$27,$4A,$8F
db $07,$27,$4B,$8F
db $01,$27,$4C,$8F
db $07,$27,$4C,$90
db $05,$27,$4D,$90
db $03,$27,$4D,$91
db $07,$27,$4E,$91
db $01,$27,$4F,$91
db $07,$27,$4F,$92
db $04,$27,$50,$92
db $03,$27,$50,$93
db $08,$27,$51,$93
db $08,$27,$52,$94
db $04,$27,$53,$94
db $03,$27,$53,$95
db $04,$27,$54,$95
db $08,$28,$54,$95
db $03,$29,$54,$95
db $01,$29,$55,$95
db $04,$29,$55,$96
db $08,$2A,$55,$96
db $05,$2B,$55,$96
db $03,$2B,$56,$96
db $08,$2C,$56,$96
db $07,$2D,$56,$97
db $01,$2D,$57,$97
db $08,$2E,$57,$97
db $08,$2F,$57,$97
db $04,$30,$57,$97
db $05,$30,$58,$97
db $09,$31,$58,$97
db $09,$32,$58,$98
db $05,$33,$58,$98
db $04,$33,$59,$98
db $09,$34,$59,$98
db $0B,$35,$59,$98
db $02,$36,$59,$98
db $0B,$36,$5A,$98
db $0C,$37,$5A,$98
db $04,$38,$5B,$98
db $08,$38,$5B,$99
db $0B,$39,$5B,$99
db $01,$39,$5C,$99
db $0C,$3A,$5C,$99
db $09,$3B,$5C,$99
db $03,$3B,$5D,$99
db $0C,$3C,$5D,$99
db $08,$3D,$5D,$99
db $04,$3D,$5E,$99
db $04,$3E,$5E,$99
db $02,$3E,$5E,$9A
db $0D,$3E,$5E,$99
db $0F,$3F,$5E,$99
db $02,$3F,$5D,$98
db $04,$3E,$5D,$98
db $02,$3E,$5C,$98
db $04,$3E,$5C,$97
db $01,$3D,$5C,$97
db $02,$3D,$5B,$97
db $04,$3D,$5B,$96
db $03,$3D,$5A,$96
db $03,$3C,$5A,$95
db $04,$3C,$59,$95
db $03,$3C,$59,$94
db $05,$3B,$58,$94
db $01,$3B,$58,$93
db $05,$3B,$57,$93
db $01,$3A,$57,$93
db $25,$3A,$56,$92
db $00
